FROM node:13.13.0-alpine
# Create app directory
WORKDIR /usr/src/app

COPY package*.json ./

# Install app dependencies
RUN npm install
# Bundle app source
COPY . .
ENV KAFKA_HOST=localhost:9092 \
    KAFKA_TOPIC=tweetstream \
    KAFKA_PROCESSED_TOPIC=processedData \
    SENTIMENT_API_ENDPOINT=http://localhost:5000/predict \
    TWEET_STORE_ENDPOINT=http://localhost:4000/tweets

CMD ["npm", "start"]   