FROM node:13.13.0-alpine

# Install python in node:slim  base image
# RUN apt-get update || : && apt-get install python -y

# Install python in node:alpine base image
#RUN apk add g++ make python

# Create app directory
WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

# Bundle app source
COPY . .

# Install NTPD for time synchronization and timezone data.
# RUN apk --no-cache update && \
#     apk --no-cache upgrade && \
#     apk --no-cache add tzdata openntpd 
    # && \
    # apk --update add bash && \
    # apk add dos2unix

# RUN dos2unix ./startup.sh
# ENV KAFKA_HOST=localhost:9092 \
#     KAFKA_TOPIC=tweetstream 
    # SET_CONTAINER_TIMEZONE=true \ 
    # CONTAINER_TIMEZONE=America/New_York

# ENTRYPOINT ["./startup.sh"]

CMD [ "npm", "start" ]

# CMD ["dos2unix","./startup.sh"]